config/routes.rb
Rails.application.routes.draw do

	devise_for :users
  resources :users,only: [:show,:edit,:update,:index]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  root 'home#top'
  get 'home/about'
  get '/search' => 'search#search'

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image, destroy: false

  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: {maximum: 50}

  has_many :books
  has_many :favorites

# フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
    def user_params
       params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数 : <%= user.followings.count%></td>
        <td>フォロワー数 : <%= user.followers.count%></td>
        <td><%= render 'relationships/simplefollow', user: user%></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
      <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><a href="<%= following_user_path(user) %>"><%= user.followings.count %></a></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><a href="<%= followers_user_path(user) %>"><%= user.followers.count %></a></th>
      </tr>
</div>
</table>
<% if user == current_user %>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='row'>

  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Users</h2>

    <%= render 'index',users: @users %>
  </div>

</div>

app/views/users/show.html.erb
<div class='row'>

  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user,now: ''%><br>
    <%= render 'relationships/follow', user: @user %>
    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'books/index',books: @books %>
  </div>
</div>

app/views/users/show_follow.html.erb
<h2>Follow Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.followings.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show_follower.html.erb
<h2>Follower Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.followers.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>