config/routes.rb
Rails.application.routes.draw do

	devise_for :users
  resources :users,only: [:show,:edit,:update,:index]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  root 'home#top'
  get 'home/about'
  get '/search' => 'search#search'

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body ,presence: true, length: {maximum: 200}
	has_many :favorites
	has_many :book_comments

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    screen_user(@book)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def screen_user(book)
      if book.user.id != current_user.id
        redirect_to books_path
      end
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr>

  <td><%= link_to(book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
    <% end %>
  </td>
  <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
  <td><%= book.body %></td>

  <!-- いいね機能 -->
  <td id='favorite-<%= book.id%>'>
    <%= render 'favorites/favorite', book: book%>
  </td>
  <td>コメント数：<%= book.book_comments.count %></td>

  <% if @book.user == current_user %>
    <td><%= link_to 'Edit', edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
    <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{@book.id}"%></td>
  <% end %>

</tr>

app/views/books/_book_comment.html.erb
<table id="comment_area" class="table">
	<% book_comments.each do |book_comment| %> <!-- コメント一覧 -->
		<%= render 'books/comment', book_comment: book_comment%>
	<% end %>
</table>

app/views/books/_comment.html.erb
<tr id= "book_comment-<%= book_comment.id%>">
	<td>
		<%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
			<%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
			<%= book_comment.user.name %>
		<% end %>
	</td>
	<td><%= book_comment.comment %></td>
	<% unless current_user != book_comment.user %>
		<td><%= link_to 'Destroy', book_book_comments_path(book_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
	<% end %>
</tr>

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <%= render 'books/book', book: book %>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> -->
  	<%= render 'layouts/errors', obj: @book %>
		<%= render 'form', book: @book %>
		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
		<%= link_to 'Back', books_path, class: "back" %>
    </div>
    <div class='col-md-3'></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: current_user %>

    <h2>New book</h2>
    <%= render 'form', book: @book %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'index', books: @books%>
  </div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
    <%= render '/books/form', book: Book.new %>
  </div>


  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table id="book" class='table'>
		  <%= render 'books/book', book: @book %>
    </table>
    <h3>Book comment</h3>
      <%= render 'books/book_comment' , book_comments: @book_comments %>
    <div id="comment-form">
      <%= form_with model: [@book, @book_comment], remote: true do |f| %>
        <%= f.text_area :comment, size: "90x5" %>
        <%= f.submit '送信' %>
      <% end %>
    </div>

  </div>
</div>